In [ ]:
import keras
from keras.applications import VGG16
#from keras.preprocessing.image import ImageDataGenerator
from keras.models import Model
from keras.layers import Dense, GlobalAveragePooling2D

In [ ]:
vgg16 = VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

58889256/58889256 [==============================] - 0s 0us/step


https://keras.io/api/layers/core_layers/dense/

In [ ]:
x = vgg16.output
x = GlobalAveragePooling2D()(x)
x = Dense(1, activation='sigmoid')(x)

In [ ]:
model = Model(inputs=vgg16.input, outputs=x)

In [ ]:
model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

In [ ]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0     

In [ ]:
import numpy as np
from keras.applications.vgg16 import preprocess_input

In [ ]:
img_path = 'frac01.jpg'
img = keras.utils.load_img(img_path, target_size=(224, 224))
inp = keras.utils.img_to_array(img)
inp = np.expand_dims(inp, axis=0)
inp = preprocess_input(inp)

features1 = model.predict(inp)
features1

1/1 [==============================] - 1s 769ms/step


array([[0.615931]], dtype=float32)

In [ ]:
img_path = 'frac02.jpg'
img = keras.utils.load_img(img_path, target_size=(224, 224))
inp = keras.utils.img_to_array(img)
inp = np.expand_dims(inp, axis=0)
inp = preprocess_input(inp)

features2 = model.predict(inp)
features2

1/1 [==============================] - 1s 1s/step


array([[0.9907025]], dtype=float32)

In [ ]:
img_path = 'nonfrac01.jpg'
img = keras.utils.load_img(img_path, target_size=(224, 224))
inp = keras.utils.img_to_array(img)
inp = np.expand_dims(inp, axis=0)
inp = preprocess_input(inp)

features3 = model.predict(inp)
features3

1/1 [==============================] - 1s 1s/step


array([[0.99518645]], dtype=float32)

In [ ]:
img_path = 'nonfrac02.jpg'
img = keras.utils.load_img(img_path, target_size=(224, 224))
inp = keras.utils.img_to_array(img)
inp = np.expand_dims(inp, axis=0)
inp = preprocess_input(inp)

features4 = model.predict(inp)
features4

1/1 [==============================] - 1s 807ms/step


array([[0.9520262]], dtype=float32)